---

# Database settings.
postgres_db_user: "vagrant"
postgres_db_name: "{{ application_name }}"
postgres_db_password: ""


# Application settings.
virtualenv_path: "/home/vagrant/.env"
project_path: "/vagrant"
requirements_file: "{{ project_path }}/requirements/local.txt"
django_settings_path: "{{ project_path }}/config/settings"
django_settings: "config.settings.local"

# Path for .env file
#env_dev: "../env.yml"
#env_path: "{{ django_settings_path }}/.env"
