---
{% raw %}
- name: Create a {{ application_name }} virtual machine via vagrant
  hosts: all
  sudo: yes
  sudo_user: root
  remote_user: vagrant
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
  vars_files:
    - host_vars/base.yml
    - host_vars/vagrant.yml

  roles:
    - common
    - postgresql
    - postgis
    - redis
    - bower
    - app
{% endraw %}