---
{% raw %}
- name: Install PostGIS
  apt: name={{ item }} update_cache=yes state=installed
  with_items:
    - postgis
    - postgresql-9.4-postgis-2.1
  tags: packages

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

- name: Ensure database is created
  sudo_user: postgres
  postgresql_db: name={{ db_name }}
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 template='template0'
                 state=present
  notify:
    - convert database to postgis
    - convert database to postgis topology

  tags:
    postgis
{% endraw %}